# Generated by Django 2.1.4 on 2019-02-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecount',
            old_name='like_unm',
            new_name='like_num',
        ),
    ]
