# Generated by Django 2.1.4 on 2018-12-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181224_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readed_unm',
            field=models.IntegerField(default=0),
        ),
    ]
