# Generated by Django 2.1.4 on 2018-12-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_readed_unm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='readed_unm',
            new_name='read_unm',
        ),
    ]
