# Generated by Django 2.1.4 on 2018-12-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181224_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='read_unm',
            new_name='read_num',
        ),
    ]
